### ISSUE TITLE
Solidi curvilinei

### ISSUE THREAD

**Issue by doriafederico** [Forcellato/Engine3D#1]
Ciao! Grazie per il tuo impegno nello sviluppo di una comunità di prodotti open source, è proprio un bell'insegnamento! Volevo sapere però come posso creare degli oggetti curvilinei perchè mi sono stancato di quei semplici quadrati che posso fare anche a mano, ciao e buona giornata!

**Comment by Forcellato** [comment]
Devi implementare i metodi con cui disegni il solido. É un problema dello sviluppatore riuscire a creare delle curve tra i nodi di un solido.

**Comment by doriafederico** [comment]
Tutto questo giro di parole per dirmi semplicemente che non sei stato in grado di farlo te?
